from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server.models.pagination import Pagination
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501
from openapi_server.models.pagination import Pagination  # noqa: E501

class BookListResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None, pagination=None):  # noqa: E501
        """BookListResponseData - a model defined in OpenAPI

        :param books: The books of this BookListResponseData.  # noqa: E501
        :type books: List[Book]
        :param pagination: The pagination of this BookListResponseData.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'books': List[Book],
            'pagination': Pagination
        }

        self.attribute_map = {
            'books': 'books',
            'pagination': 'pagination'
        }

        self._books = books
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'BookListResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookListResponse_data of this BookListResponseData.  # noqa: E501
        :rtype: BookListResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this BookListResponseData.


        :return: The books of this BookListResponseData.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this BookListResponseData.


        :param books: The books of this BookListResponseData.
        :type books: List[Book]
        """

        self._books = books

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this BookListResponseData.


        :return: The pagination of this BookListResponseData.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this BookListResponseData.


        :param pagination: The pagination of this BookListResponseData.
        :type pagination: Pagination
        """

        self._pagination = pagination
