from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Book(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, isbn=None, available=None, created_at=None):  # noqa: E501
        """Book - a model defined in OpenAPI

        :param id: The id of this Book.  # noqa: E501
        :type id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param isbn: The isbn of this Book.  # noqa: E501
        :type isbn: str
        :param available: The available of this Book.  # noqa: E501
        :type available: bool
        :param created_at: The created_at of this Book.  # noqa: E501
        :type created_at: datetime
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'author': str,
            'isbn': str,
            'available': bool,
            'created_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'isbn': 'isbn',
            'available': 'available',
            'created_at': 'created_at'
        }

        self._id = id
        self._title = title
        self._author = author
        self._isbn = isbn
        self._available = available
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Book.


        :return: The id of this Book.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Book.


        :param id: The id of this Book.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.

        Book title  # noqa: E501

        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.

        Book title  # noqa: E501

        :param title: The title of this Book.
        :type title: str
        """
        if title is not None and len(title) > 100:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `100`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.

        Book author  # noqa: E501

        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.

        Book author  # noqa: E501

        :param author: The author of this Book.
        :type author: str
        """
        if author is not None and len(author) > 100:
            raise ValueError("Invalid value for `author`, length must be less than or equal to `100`")  # noqa: E501

        self._author = author

    @property
    def isbn(self) -> str:
        """Gets the isbn of this Book.

        ISBN number  # noqa: E501

        :return: The isbn of this Book.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this Book.

        ISBN number  # noqa: E501

        :param isbn: The isbn of this Book.
        :type isbn: str
        """
        if isbn is not None and len(isbn) > 13:
            raise ValueError("Invalid value for `isbn`, length must be less than or equal to `13`")  # noqa: E501

        self._isbn = isbn

    @property
    def available(self) -> bool:
        """Gets the available of this Book.

        Availability status  # noqa: E501

        :return: The available of this Book.
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available: bool):
        """Sets the available of this Book.

        Availability status  # noqa: E501

        :param available: The available of this Book.
        :type available: bool
        """

        self._available = available

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Book.


        :return: The created_at of this Book.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Book.


        :param created_at: The created_at of this Book.
        :type created_at: datetime
        """

        self._created_at = created_at
