from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501

class BorrowRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, book_id=None, book=None, borrower_name=None, borrower_email=None, borrow_date=None, due_date=None, return_date=None, returned=None, is_overdue=None):  # noqa: E501
        """BorrowRecord - a model defined in OpenAPI

        :param id: The id of this BorrowRecord.  # noqa: E501
        :type id: int
        :param book_id: The book_id of this BorrowRecord.  # noqa: E501
        :type book_id: int
        :param book: The book of this BorrowRecord.  # noqa: E501
        :type book: Book
        :param borrower_name: The borrower_name of this BorrowRecord.  # noqa: E501
        :type borrower_name: str
        :param borrower_email: The borrower_email of this BorrowRecord.  # noqa: E501
        :type borrower_email: str
        :param borrow_date: The borrow_date of this BorrowRecord.  # noqa: E501
        :type borrow_date: datetime
        :param due_date: The due_date of this BorrowRecord.  # noqa: E501
        :type due_date: datetime
        :param return_date: The return_date of this BorrowRecord.  # noqa: E501
        :type return_date: datetime
        :param returned: The returned of this BorrowRecord.  # noqa: E501
        :type returned: bool
        :param is_overdue: The is_overdue of this BorrowRecord.  # noqa: E501
        :type is_overdue: bool
        """
        self.openapi_types = {
            'id': int,
            'book_id': int,
            'book': Book,
            'borrower_name': str,
            'borrower_email': str,
            'borrow_date': datetime,
            'due_date': datetime,
            'return_date': datetime,
            'returned': bool,
            'is_overdue': bool
        }

        self.attribute_map = {
            'id': 'id',
            'book_id': 'book_id',
            'book': 'book',
            'borrower_name': 'borrower_name',
            'borrower_email': 'borrower_email',
            'borrow_date': 'borrow_date',
            'due_date': 'due_date',
            'return_date': 'return_date',
            'returned': 'returned',
            'is_overdue': 'is_overdue'
        }

        self._id = id
        self._book_id = book_id
        self._book = book
        self._borrower_name = borrower_name
        self._borrower_email = borrower_email
        self._borrow_date = borrow_date
        self._due_date = due_date
        self._return_date = return_date
        self._returned = returned
        self._is_overdue = is_overdue

    @classmethod
    def from_dict(cls, dikt) -> 'BorrowRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BorrowRecord of this BorrowRecord.  # noqa: E501
        :rtype: BorrowRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this BorrowRecord.


        :return: The id of this BorrowRecord.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this BorrowRecord.


        :param id: The id of this BorrowRecord.
        :type id: int
        """

        self._id = id

    @property
    def book_id(self) -> int:
        """Gets the book_id of this BorrowRecord.


        :return: The book_id of this BorrowRecord.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this BorrowRecord.


        :param book_id: The book_id of this BorrowRecord.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def book(self) -> Book:
        """Gets the book of this BorrowRecord.


        :return: The book of this BorrowRecord.
        :rtype: Book
        """
        return self._book

    @book.setter
    def book(self, book: Book):
        """Sets the book of this BorrowRecord.


        :param book: The book of this BorrowRecord.
        :type book: Book
        """

        self._book = book

    @property
    def borrower_name(self) -> str:
        """Gets the borrower_name of this BorrowRecord.


        :return: The borrower_name of this BorrowRecord.
        :rtype: str
        """
        return self._borrower_name

    @borrower_name.setter
    def borrower_name(self, borrower_name: str):
        """Sets the borrower_name of this BorrowRecord.


        :param borrower_name: The borrower_name of this BorrowRecord.
        :type borrower_name: str
        """

        self._borrower_name = borrower_name

    @property
    def borrower_email(self) -> str:
        """Gets the borrower_email of this BorrowRecord.


        :return: The borrower_email of this BorrowRecord.
        :rtype: str
        """
        return self._borrower_email

    @borrower_email.setter
    def borrower_email(self, borrower_email: str):
        """Sets the borrower_email of this BorrowRecord.


        :param borrower_email: The borrower_email of this BorrowRecord.
        :type borrower_email: str
        """

        self._borrower_email = borrower_email

    @property
    def borrow_date(self) -> datetime:
        """Gets the borrow_date of this BorrowRecord.


        :return: The borrow_date of this BorrowRecord.
        :rtype: datetime
        """
        return self._borrow_date

    @borrow_date.setter
    def borrow_date(self, borrow_date: datetime):
        """Sets the borrow_date of this BorrowRecord.


        :param borrow_date: The borrow_date of this BorrowRecord.
        :type borrow_date: datetime
        """

        self._borrow_date = borrow_date

    @property
    def due_date(self) -> datetime:
        """Gets the due_date of this BorrowRecord.


        :return: The due_date of this BorrowRecord.
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date: datetime):
        """Sets the due_date of this BorrowRecord.


        :param due_date: The due_date of this BorrowRecord.
        :type due_date: datetime
        """

        self._due_date = due_date

    @property
    def return_date(self) -> datetime:
        """Gets the return_date of this BorrowRecord.


        :return: The return_date of this BorrowRecord.
        :rtype: datetime
        """
        return self._return_date

    @return_date.setter
    def return_date(self, return_date: datetime):
        """Sets the return_date of this BorrowRecord.


        :param return_date: The return_date of this BorrowRecord.
        :type return_date: datetime
        """

        self._return_date = return_date

    @property
    def returned(self) -> bool:
        """Gets the returned of this BorrowRecord.


        :return: The returned of this BorrowRecord.
        :rtype: bool
        """
        return self._returned

    @returned.setter
    def returned(self, returned: bool):
        """Sets the returned of this BorrowRecord.


        :param returned: The returned of this BorrowRecord.
        :type returned: bool
        """

        self._returned = returned

    @property
    def is_overdue(self) -> bool:
        """Gets the is_overdue of this BorrowRecord.


        :return: The is_overdue of this BorrowRecord.
        :rtype: bool
        """
        return self._is_overdue

    @is_overdue.setter
    def is_overdue(self, is_overdue: bool):
        """Sets the is_overdue of this BorrowRecord.


        :param is_overdue: The is_overdue of this BorrowRecord.
        :type is_overdue: bool
        """

        self._is_overdue = is_overdue
