from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BorrowInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book_id=None, borrower_name=None, borrower_email=None, days=14):  # noqa: E501
        """BorrowInput - a model defined in OpenAPI

        :param book_id: The book_id of this BorrowInput.  # noqa: E501
        :type book_id: int
        :param borrower_name: The borrower_name of this BorrowInput.  # noqa: E501
        :type borrower_name: str
        :param borrower_email: The borrower_email of this BorrowInput.  # noqa: E501
        :type borrower_email: str
        :param days: The days of this BorrowInput.  # noqa: E501
        :type days: int
        """
        self.openapi_types = {
            'book_id': int,
            'borrower_name': str,
            'borrower_email': str,
            'days': int
        }

        self.attribute_map = {
            'book_id': 'book_id',
            'borrower_name': 'borrower_name',
            'borrower_email': 'borrower_email',
            'days': 'days'
        }

        self._book_id = book_id
        self._borrower_name = borrower_name
        self._borrower_email = borrower_email
        self._days = days

    @classmethod
    def from_dict(cls, dikt) -> 'BorrowInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BorrowInput of this BorrowInput.  # noqa: E501
        :rtype: BorrowInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_id(self) -> int:
        """Gets the book_id of this BorrowInput.

        ID of the book to borrow  # noqa: E501

        :return: The book_id of this BorrowInput.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this BorrowInput.

        ID of the book to borrow  # noqa: E501

        :param book_id: The book_id of this BorrowInput.
        :type book_id: int
        """
        if book_id is None:
            raise ValueError("Invalid value for `book_id`, must not be `None`")  # noqa: E501

        self._book_id = book_id

    @property
    def borrower_name(self) -> str:
        """Gets the borrower_name of this BorrowInput.


        :return: The borrower_name of this BorrowInput.
        :rtype: str
        """
        return self._borrower_name

    @borrower_name.setter
    def borrower_name(self, borrower_name: str):
        """Sets the borrower_name of this BorrowInput.


        :param borrower_name: The borrower_name of this BorrowInput.
        :type borrower_name: str
        """
        if borrower_name is None:
            raise ValueError("Invalid value for `borrower_name`, must not be `None`")  # noqa: E501
        if borrower_name is not None and len(borrower_name) > 100:
            raise ValueError("Invalid value for `borrower_name`, length must be less than or equal to `100`")  # noqa: E501

        self._borrower_name = borrower_name

    @property
    def borrower_email(self) -> str:
        """Gets the borrower_email of this BorrowInput.


        :return: The borrower_email of this BorrowInput.
        :rtype: str
        """
        return self._borrower_email

    @borrower_email.setter
    def borrower_email(self, borrower_email: str):
        """Sets the borrower_email of this BorrowInput.


        :param borrower_email: The borrower_email of this BorrowInput.
        :type borrower_email: str
        """
        if borrower_email is None:
            raise ValueError("Invalid value for `borrower_email`, must not be `None`")  # noqa: E501
        if borrower_email is not None and len(borrower_email) > 100:
            raise ValueError("Invalid value for `borrower_email`, length must be less than or equal to `100`")  # noqa: E501

        self._borrower_email = borrower_email

    @property
    def days(self) -> int:
        """Gets the days of this BorrowInput.

        Borrowing period in days  # noqa: E501

        :return: The days of this BorrowInput.
        :rtype: int
        """
        return self._days

    @days.setter
    def days(self, days: int):
        """Sets the days of this BorrowInput.

        Borrowing period in days  # noqa: E501

        :param days: The days of this BorrowInput.
        :type days: int
        """
        if days is not None and days > 90:  # noqa: E501
            raise ValueError("Invalid value for `days`, must be a value less than or equal to `90`")  # noqa: E501
        if days is not None and days < 1:  # noqa: E501
            raise ValueError("Invalid value for `days`, must be a value greater than or equal to `1`")  # noqa: E501

        self._days = days
