from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501

class CreateBook201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None, data=None):  # noqa: E501
        """CreateBook201Response - a model defined in OpenAPI

        :param success: The success of this CreateBook201Response.  # noqa: E501
        :type success: bool
        :param message: The message of this CreateBook201Response.  # noqa: E501
        :type message: str
        :param data: The data of this CreateBook201Response.  # noqa: E501
        :type data: Book
        """
        self.openapi_types = {
            'success': bool,
            'message': str,
            'data': Book
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message',
            'data': 'data'
        }

        self._success = success
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CreateBook201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createBook_201_response of this CreateBook201Response.  # noqa: E501
        :rtype: CreateBook201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this CreateBook201Response.


        :return: The success of this CreateBook201Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this CreateBook201Response.


        :param success: The success of this CreateBook201Response.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this CreateBook201Response.


        :return: The message of this CreateBook201Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CreateBook201Response.


        :param message: The message of this CreateBook201Response.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Book:
        """Gets the data of this CreateBook201Response.


        :return: The data of this CreateBook201Response.
        :rtype: Book
        """
        return self._data

    @data.setter
    def data(self, data: Book):
        """Sets the data of this CreateBook201Response.


        :param data: The data of this CreateBook201Response.
        :type data: Book
        """

        self._data = data
