from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ExtendInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, additional_days=None):  # noqa: E501
        """ExtendInput - a model defined in OpenAPI

        :param additional_days: The additional_days of this ExtendInput.  # noqa: E501
        :type additional_days: int
        """
        self.openapi_types = {
            'additional_days': int
        }

        self.attribute_map = {
            'additional_days': 'additional_days'
        }

        self._additional_days = additional_days

    @classmethod
    def from_dict(cls, dikt) -> 'ExtendInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExtendInput of this ExtendInput.  # noqa: E501
        :rtype: ExtendInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def additional_days(self) -> int:
        """Gets the additional_days of this ExtendInput.

        Additional days to extend the due date  # noqa: E501

        :return: The additional_days of this ExtendInput.
        :rtype: int
        """
        return self._additional_days

    @additional_days.setter
    def additional_days(self, additional_days: int):
        """Sets the additional_days of this ExtendInput.

        Additional days to extend the due date  # noqa: E501

        :param additional_days: The additional_days of this ExtendInput.
        :type additional_days: int
        """
        if additional_days is None:
            raise ValueError("Invalid value for `additional_days`, must not be `None`")  # noqa: E501
        if additional_days is not None and additional_days > 30:  # noqa: E501
            raise ValueError("Invalid value for `additional_days`, must be a value less than or equal to `30`")  # noqa: E501
        if additional_days is not None and additional_days < 1:  # noqa: E501
            raise ValueError("Invalid value for `additional_days`, must be a value greater than or equal to `1`")  # noqa: E501

        self._additional_days = additional_days
