from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.borrow_record import BorrowRecord
from openapi_server.models.pagination import Pagination
from openapi_server import util

from openapi_server.models.borrow_record import BorrowRecord  # noqa: E501
from openapi_server.models.pagination import Pagination  # noqa: E501

class GetBorrows200ResponseAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, borrows=None, pagination=None):  # noqa: E501
        """GetBorrows200ResponseAllOfData - a model defined in OpenAPI

        :param borrows: The borrows of this GetBorrows200ResponseAllOfData.  # noqa: E501
        :type borrows: List[BorrowRecord]
        :param pagination: The pagination of this GetBorrows200ResponseAllOfData.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'borrows': List[BorrowRecord],
            'pagination': Pagination
        }

        self.attribute_map = {
            'borrows': 'borrows',
            'pagination': 'pagination'
        }

        self._borrows = borrows
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'GetBorrows200ResponseAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getBorrows_200_response_allOf_data of this GetBorrows200ResponseAllOfData.  # noqa: E501
        :rtype: GetBorrows200ResponseAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def borrows(self) -> List[BorrowRecord]:
        """Gets the borrows of this GetBorrows200ResponseAllOfData.


        :return: The borrows of this GetBorrows200ResponseAllOfData.
        :rtype: List[BorrowRecord]
        """
        return self._borrows

    @borrows.setter
    def borrows(self, borrows: List[BorrowRecord]):
        """Sets the borrows of this GetBorrows200ResponseAllOfData.


        :param borrows: The borrows of this GetBorrows200ResponseAllOfData.
        :type borrows: List[BorrowRecord]
        """

        self._borrows = borrows

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this GetBorrows200ResponseAllOfData.


        :return: The pagination of this GetBorrows200ResponseAllOfData.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this GetBorrows200ResponseAllOfData.


        :param pagination: The pagination of this GetBorrows200ResponseAllOfData.
        :type pagination: Pagination
        """

        self._pagination = pagination
