from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Pagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_page=None, per_page=None, total_items=None, total_pages=None, has_next=None, has_prev=None, next_page=None, prev_page=None):  # noqa: E501
        """Pagination - a model defined in OpenAPI

        :param current_page: The current_page of this Pagination.  # noqa: E501
        :type current_page: int
        :param per_page: The per_page of this Pagination.  # noqa: E501
        :type per_page: int
        :param total_items: The total_items of this Pagination.  # noqa: E501
        :type total_items: int
        :param total_pages: The total_pages of this Pagination.  # noqa: E501
        :type total_pages: int
        :param has_next: The has_next of this Pagination.  # noqa: E501
        :type has_next: bool
        :param has_prev: The has_prev of this Pagination.  # noqa: E501
        :type has_prev: bool
        :param next_page: The next_page of this Pagination.  # noqa: E501
        :type next_page: int
        :param prev_page: The prev_page of this Pagination.  # noqa: E501
        :type prev_page: int
        """
        self.openapi_types = {
            'current_page': int,
            'per_page': int,
            'total_items': int,
            'total_pages': int,
            'has_next': bool,
            'has_prev': bool,
            'next_page': int,
            'prev_page': int
        }

        self.attribute_map = {
            'current_page': 'current_page',
            'per_page': 'per_page',
            'total_items': 'total_items',
            'total_pages': 'total_pages',
            'has_next': 'has_next',
            'has_prev': 'has_prev',
            'next_page': 'next_page',
            'prev_page': 'prev_page'
        }

        self._current_page = current_page
        self._per_page = per_page
        self._total_items = total_items
        self._total_pages = total_pages
        self._has_next = has_next
        self._has_prev = has_prev
        self._next_page = next_page
        self._prev_page = prev_page

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_page(self) -> int:
        """Gets the current_page of this Pagination.


        :return: The current_page of this Pagination.
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page: int):
        """Sets the current_page of this Pagination.


        :param current_page: The current_page of this Pagination.
        :type current_page: int
        """

        self._current_page = current_page

    @property
    def per_page(self) -> int:
        """Gets the per_page of this Pagination.


        :return: The per_page of this Pagination.
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page: int):
        """Sets the per_page of this Pagination.


        :param per_page: The per_page of this Pagination.
        :type per_page: int
        """

        self._per_page = per_page

    @property
    def total_items(self) -> int:
        """Gets the total_items of this Pagination.


        :return: The total_items of this Pagination.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items: int):
        """Sets the total_items of this Pagination.


        :param total_items: The total_items of this Pagination.
        :type total_items: int
        """

        self._total_items = total_items

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this Pagination.


        :return: The total_pages of this Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this Pagination.


        :param total_pages: The total_pages of this Pagination.
        :type total_pages: int
        """

        self._total_pages = total_pages

    @property
    def has_next(self) -> bool:
        """Gets the has_next of this Pagination.


        :return: The has_next of this Pagination.
        :rtype: bool
        """
        return self._has_next

    @has_next.setter
    def has_next(self, has_next: bool):
        """Sets the has_next of this Pagination.


        :param has_next: The has_next of this Pagination.
        :type has_next: bool
        """

        self._has_next = has_next

    @property
    def has_prev(self) -> bool:
        """Gets the has_prev of this Pagination.


        :return: The has_prev of this Pagination.
        :rtype: bool
        """
        return self._has_prev

    @has_prev.setter
    def has_prev(self, has_prev: bool):
        """Sets the has_prev of this Pagination.


        :param has_prev: The has_prev of this Pagination.
        :type has_prev: bool
        """

        self._has_prev = has_prev

    @property
    def next_page(self) -> int:
        """Gets the next_page of this Pagination.


        :return: The next_page of this Pagination.
        :rtype: int
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page: int):
        """Sets the next_page of this Pagination.


        :param next_page: The next_page of this Pagination.
        :type next_page: int
        """

        self._next_page = next_page

    @property
    def prev_page(self) -> int:
        """Gets the prev_page of this Pagination.


        :return: The prev_page of this Pagination.
        :rtype: int
        """
        return self._prev_page

    @prev_page.setter
    def prev_page(self, prev_page: int):
        """Sets the prev_page of this Pagination.


        :param prev_page: The prev_page of this Pagination.
        :type prev_page: int
        """

        self._prev_page = prev_page
