from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RefreshTokenRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, refresh_token=None):  # noqa: E501
        """RefreshTokenRequest - a model defined in OpenAPI

        :param refresh_token: The refresh_token of this RefreshTokenRequest.  # noqa: E501
        :type refresh_token: str
        """
        self.openapi_types = {
            'refresh_token': str
        }

        self.attribute_map = {
            'refresh_token': 'refresh_token'
        }

        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'RefreshTokenRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RefreshTokenRequest of this RefreshTokenRequest.  # noqa: E501
        :rtype: RefreshTokenRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this RefreshTokenRequest.

        Refresh token to obtain new access token  # noqa: E501

        :return: The refresh_token of this RefreshTokenRequest.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this RefreshTokenRequest.

        Refresh token to obtain new access token  # noqa: E501

        :param refresh_token: The refresh_token of this RefreshTokenRequest.
        :type refresh_token: str
        """
        if refresh_token is None:
            raise ValueError("Invalid value for `refresh_token`, must not be `None`")  # noqa: E501

        self._refresh_token = refresh_token
