from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RefreshToken200ResponseAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_token=None):  # noqa: E501
        """RefreshToken200ResponseAllOfData - a model defined in OpenAPI

        :param access_token: The access_token of this RefreshToken200ResponseAllOfData.  # noqa: E501
        :type access_token: str
        """
        self.openapi_types = {
            'access_token': str
        }

        self.attribute_map = {
            'access_token': 'access_token'
        }

        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'RefreshToken200ResponseAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The refreshToken_200_response_allOf_data of this RefreshToken200ResponseAllOfData.  # noqa: E501
        :rtype: RefreshToken200ResponseAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this RefreshToken200ResponseAllOfData.


        :return: The access_token of this RefreshToken200ResponseAllOfData.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this RefreshToken200ResponseAllOfData.


        :param access_token: The access_token of this RefreshToken200ResponseAllOfData.
        :type access_token: str
        """

        self._access_token = access_token
