from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, email=None, password=None, full_name=None):  # noqa: E501
        """RegisterRequest - a model defined in OpenAPI

        :param username: The username of this RegisterRequest.  # noqa: E501
        :type username: str
        :param email: The email of this RegisterRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterRequest.  # noqa: E501
        :type password: str
        :param full_name: The full_name of this RegisterRequest.  # noqa: E501
        :type full_name: str
        """
        self.openapi_types = {
            'username': str,
            'email': str,
            'password': str,
            'full_name': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'password': 'password',
            'full_name': 'full_name'
        }

        self._username = username
        self._email = email
        self._password = password
        self._full_name = full_name

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterRequest of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this RegisterRequest.

        Unique username  # noqa: E501

        :return: The username of this RegisterRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegisterRequest.

        Unique username  # noqa: E501

        :param username: The username of this RegisterRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 50:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `50`")  # noqa: E501
        if username is not None and len(username) < 3:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `3`")  # noqa: E501

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this RegisterRequest.

        User email address  # noqa: E501

        :return: The email of this RegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterRequest.

        User email address  # noqa: E501

        :param email: The email of this RegisterRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this RegisterRequest.

        User password (minimum 6 characters)  # noqa: E501

        :return: The password of this RegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterRequest.

        User password (minimum 6 characters)  # noqa: E501

        :param password: The password of this RegisterRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) < 6:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `6`")  # noqa: E501

        self._password = password

    @property
    def full_name(self) -> str:
        """Gets the full_name of this RegisterRequest.

        Full name of the user  # noqa: E501

        :return: The full_name of this RegisterRequest.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this RegisterRequest.

        Full name of the user  # noqa: E501

        :param full_name: The full_name of this RegisterRequest.
        :type full_name: str
        """
        if full_name is not None and len(full_name) > 100:
            raise ValueError("Invalid value for `full_name`, length must be less than or equal to `100`")  # noqa: E501

        self._full_name = full_name
