from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.verify_token200_response_all_of_data import VerifyToken200ResponseAllOfData
from openapi_server import util

from openapi_server.models.verify_token200_response_all_of_data import VerifyToken200ResponseAllOfData  # noqa: E501

class VerifyToken200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None, data=None):  # noqa: E501
        """VerifyToken200Response - a model defined in OpenAPI

        :param success: The success of this VerifyToken200Response.  # noqa: E501
        :type success: bool
        :param message: The message of this VerifyToken200Response.  # noqa: E501
        :type message: str
        :param data: The data of this VerifyToken200Response.  # noqa: E501
        :type data: VerifyToken200ResponseAllOfData
        """
        self.openapi_types = {
            'success': bool,
            'message': str,
            'data': VerifyToken200ResponseAllOfData
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message',
            'data': 'data'
        }

        self._success = success
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyToken200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifyToken_200_response of this VerifyToken200Response.  # noqa: E501
        :rtype: VerifyToken200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this VerifyToken200Response.


        :return: The success of this VerifyToken200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this VerifyToken200Response.


        :param success: The success of this VerifyToken200Response.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this VerifyToken200Response.


        :return: The message of this VerifyToken200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this VerifyToken200Response.


        :param message: The message of this VerifyToken200Response.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> VerifyToken200ResponseAllOfData:
        """Gets the data of this VerifyToken200Response.


        :return: The data of this VerifyToken200Response.
        :rtype: VerifyToken200ResponseAllOfData
        """
        return self._data

    @data.setter
    def data(self, data: VerifyToken200ResponseAllOfData):
        """Sets the data of this VerifyToken200Response.


        :param data: The data of this VerifyToken200Response.
        :type data: VerifyToken200ResponseAllOfData
        """

        self._data = data
