from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VerifyToken200ResponseAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, valid=None, user_id=None):  # noqa: E501
        """VerifyToken200ResponseAllOfData - a model defined in OpenAPI

        :param valid: The valid of this VerifyToken200ResponseAllOfData.  # noqa: E501
        :type valid: bool
        :param user_id: The user_id of this VerifyToken200ResponseAllOfData.  # noqa: E501
        :type user_id: int
        """
        self.openapi_types = {
            'valid': bool,
            'user_id': int
        }

        self.attribute_map = {
            'valid': 'valid',
            'user_id': 'user_id'
        }

        self._valid = valid
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyToken200ResponseAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifyToken_200_response_allOf_data of this VerifyToken200ResponseAllOfData.  # noqa: E501
        :rtype: VerifyToken200ResponseAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def valid(self) -> bool:
        """Gets the valid of this VerifyToken200ResponseAllOfData.


        :return: The valid of this VerifyToken200ResponseAllOfData.
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid: bool):
        """Sets the valid of this VerifyToken200ResponseAllOfData.


        :param valid: The valid of this VerifyToken200ResponseAllOfData.
        :type valid: bool
        """

        self._valid = valid

    @property
    def user_id(self) -> int:
        """Gets the user_id of this VerifyToken200ResponseAllOfData.


        :return: The user_id of this VerifyToken200ResponseAllOfData.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this VerifyToken200ResponseAllOfData.


        :param user_id: The user_id of this VerifyToken200ResponseAllOfData.
        :type user_id: int
        """

        self._user_id = user_id
